Merge shmem branch with head
This is part 1/2 of the merge, since there's still gruntwork merging the
treewide $Source$ keyword change.

diff --git a/other/Makefile-conduit.mak.in b/other/Makefile-conduit.mak.in
--- a/other/Makefile-conduit.mak.in
+++ b/other/Makefile-conduit.mak.in
@@ -2,7 +2,7 @@
 # it is not meant to be used directly 
 # @configure_input@
 
-.PHONY: do-all do-error libs force clean-local                  \
+.PHONY: do-error libs force clean-local                  \
         do-clean-local do-install-data-local do-uninstall-local \
         do-libgasnet-seq do-libgasnet-par do-libgasnet-parsync  \
 	test tests tests-seq tests-par tests-parsync tests-clean 
@@ -15,8 +15,7 @@ headers = $(top_srcdir)/extended-ref/*.h $(srcdir)/*.h $(CONDUIT_EXTRAHEADERS)
 
 makefile_fragments =                \
         $(CONDUIT_NAME)-seq.mak     \
-        $(CONDUIT_NAME)-parsync.mak \
-	$(CONDUIT_NAME)-par.mak
+@HAVE_PTHREAD_TRUE@  $(CONDUIT_NAME)-parsync.mak $(CONDUIT_NAME)-par.mak
 
 @GASNET_SEGMENT_FAST_TRUE@GASNET_SEGMENT_STR="FAST"
 @GASNET_SEGMENT_LARGE_TRUE@GASNET_SEGMENT_STR="LARGE"
@@ -42,10 +41,11 @@ LIBCFLAGS =                       \
         @MISC_CFLAGS@             \
         $(LIBDEFINES)             \
         $(CONDUIT_EXTRALIBCFLAGS) \
-	$(LIBINCLUDES)
+	$(LIBINCLUDES)		  \
+	$(MANUAL_LIBCFLAGS)
 
 libgasnet_sources =           \
-        $(CONDUIT_SOURCELIST) \
+	$(CONDUIT_SOURCELIST) \
 	$(top_srcdir)/gasnet_internal.c	  
 
 libgasnet_objects = \
@@ -58,7 +58,7 @@ libgasnet_dependencies =                  \
         $(top_srcdir)/*.[ch]              \
         $(top_srcdir)/extended-ref/*.[ch] \
 	$(top_srcdir)/other/*.h           \
-        $(CONDUIT_SOURCELIST)             \
+	$(CONDUIT_SOURCELIST)             \
 	$(CONDUIT_EXTRAHEADERS)           \
 	$(CONDUIT_EXTRADEPS)
 
@@ -68,22 +68,43 @@ EXTRA_DIST = $(CONDUIT_FILELIST)
 THREAD_MODEL=SEQ
 THREAD_MODEL_LC=`echo "$(THREAD_MODEL)" | @AWK@ '{print tolower($$0)}'`
 do-libgasnet: $(CONDUIT_SPECIAL_OBJS)
-	$(CC) $(LIBCFLAGS) -c $(libgasnet_sources)
-	@echo $(AR) cru libgasnet-$(CONDUIT_NAME)-$(THREAD_MODEL_LC).a $(libgasnet_objects)
-	@$(AR) cru libgasnet-$(CONDUIT_NAME)-$(THREAD_MODEL_LC).a $(libgasnet_objects)
-	@echo $(RANLIB) libgasnet-$(CONDUIT_NAME)-$(THREAD_MODEL_LC).a
-	@$(RANLIB) libgasnet-$(CONDUIT_NAME)-$(THREAD_MODEL_LC).a
-	@echo rm -f $(libgasnet_objects)
-	@rm -f $(libgasnet_objects)
+	@mkdir -p .$(THREAD_MODEL)
+	@libgasnet_objects="$(libgasnet_objects)" ; libgasnet_objects=`echo $$libgasnet_objects` ; \
+	pwd=`@PWD_PROG@` ; cmd="$(CC) $(LIBCFLAGS) -c $(libgasnet_sources) && \
+	$(AR) cru $$pwd/libgasnet-$(CONDUIT_NAME)-$(THREAD_MODEL_LC).a $$libgasnet_objects && \
+	$(RANLIB) $$pwd/libgasnet-$(CONDUIT_NAME)-$(THREAD_MODEL_LC).a && \
+	rm -f $$libgasnet_objects" ; \
+	echo " --- BUILDING libgasnet-$(CONDUIT_NAME)-$(THREAD_MODEL_LC).a --- " ; \
+        echo $$cmd ; cd .$(THREAD_MODEL) ; eval $$cmd
+	@rmdir .$(THREAD_MODEL)
 
 do-libgasnet-seq: $(libgasnet_dependencies) $(CONDUIT_SEQ_HOOK)
-	@$(MAKE) THREAD_MODEL=SEQ LIBGASNET_THREAD_DEFINES= do-libgasnet
+	@$(MAKE) THREAD_MODEL=SEQ LIBGASNET_THREAD_DEFINES= \
+          top_srcdir=`cd $(top_srcdir); @PWD_PROG@`         \
+          top_builddir=`cd $(top_builddir); @PWD_PROG@`     \
+          srcdir=`cd $(srcdir); @PWD_PROG@`                 \
+          builddir=`@PWD_PROG@`                             \
+          do-libgasnet
 
 do-libgasnet-par: $(libgasnet_dependencies) $(CONDUIT_PAR_HOOK)
-	@$(MAKE) THREAD_MODEL=PAR LIBGASNET_THREAD_DEFINES="$(thread_defines)" do-libgasnet
+	@@HAVE_PTHREAD_FALSE@$(MAKE) do-pthreads-error
+	@$(MAKE) THREAD_MODEL=PAR                           \
+          LIBGASNET_THREAD_DEFINES="$(thread_defines)"      \
+          top_srcdir=`cd $(top_srcdir); @PWD_PROG@`         \
+          top_builddir=`cd $(top_builddir); @PWD_PROG@`     \
+          srcdir=`cd $(srcdir); @PWD_PROG@`                 \
+          builddir=`@PWD_PROG@`                             \
+          do-libgasnet
 
 do-libgasnet-parsync: $(libgasnet_dependencies) $(CONDUIT_PARSYNC_HOOK)
-	@$(MAKE) THREAD_MODEL=PARSYNC LIBGASNET_THREAD_DEFINES="$(thread_defines)" do-libgasnet
+	@@HAVE_PTHREAD_FALSE@$(MAKE) do-pthreads-error
+	@$(MAKE) THREAD_MODEL=PARSYNC                       \
+          LIBGASNET_THREAD_DEFINES="$(thread_defines)"      \
+          top_srcdir=`cd $(top_srcdir); @PWD_PROG@`         \
+          top_builddir=`cd $(top_builddir); @PWD_PROG@`     \
+          srcdir=`cd $(srcdir); @PWD_PROG@`                 \
+          builddir=`@PWD_PROG@`                             \
+          do-libgasnet
 
 # test targets 
 
@@ -96,17 +117,20 @@ test: tests
 tests-seq: force libgasnet-$(CONDUIT_NAME)-seq.a $(CONDUIT_NAME)-seq.mak $(CONDUIT_SEQ_HOOK)
 	@echo "*** Building all GASNet tests in SEQ/$(GASNET_SEGMENT_STR) mode ***"
 	@$(MAKE) -f $(top_builddir)/tests/Makefile tests-seq \
-	  configfile="$(CONDUIT_NAME)-seq.mak"
+	  configfile="$(CONDUIT_NAME)-seq.mak" \
+	  CONDUIT_TESTS="$(CONDUIT_TESTS)"
 
 tests-parsync: force libgasnet-$(CONDUIT_NAME)-parsync.a $(CONDUIT_NAME)-parsync.mak $(CONDUIT_PARSYNC_HOOK)
 	@echo "*** Building all GASNet tests in PARSYNC/$(GASNET_SEGMENT_STR) mode ***"
 	@$(MAKE) -f $(top_builddir)/tests/Makefile tests-parsync \
-	  configfile="$(CONDUIT_NAME)-parsync.mak"
+	  configfile="$(CONDUIT_NAME)-parsync.mak" \
+	  CONDUIT_TESTS="$(CONDUIT_TESTS)"
 
 tests-par: force libgasnet-$(CONDUIT_NAME)-par.a $(CONDUIT_NAME)-par.mak $(CONDUIT_PAR_HOOK)
 	@echo "*** Building all GASNet tests in PAR/$(GASNET_SEGMENT_STR) mode ***"
 	@$(MAKE) -f $(top_builddir)/tests/Makefile tests-par \
-	  configfile="$(CONDUIT_NAME)-par.mak"
+	  configfile="$(CONDUIT_NAME)-par.mak" \
+	  CONDUIT_TESTS="$(CONDUIT_TESTS)"
 
 test%: $(top_srcdir)/tests/test%.c force 
 	@$(MAKE) libgasnet-$(CONDUIT_NAME)-$(THREAD_MODEL_LC).a $(CONDUIT_NAME)-$(THREAD_MODEL_LC).mak
@@ -114,32 +138,45 @@ test%: $(top_srcdir)/tests/test%.c force
 	@$(MAKE) -f $(top_builddir)/tests/Makefile $@   \
 	  configfile="$(CONDUIT_NAME)-$(THREAD_MODEL_LC).mak"
 
-test%-seq: $(top_srcdir)/tests/test%.c force 
+test%: $(top_srcdir)/tests/test%.cc force 
+	@$(MAKE) libgasnet-$(CONDUIT_NAME)-$(THREAD_MODEL_LC).a $(CONDUIT_NAME)-$(THREAD_MODEL_LC).mak
+	@echo "*** Building $@ in $(THREAD_MODEL)/$(GASNET_SEGMENT_STR) mode ***"
+	@$(MAKE) -f $(top_builddir)/tests/Makefile $@   \
+	  configfile="$(CONDUIT_NAME)-$(THREAD_MODEL_LC).mak"
+
+test%-seq: force 
 	@$(MAKE) `basename $@ -seq` THREAD_MODEL=SEQ
-test%-parsync: $(top_srcdir)/tests/test%.c force 
+test%-parsync: force 
 	@$(MAKE) `basename $@ -parsync` THREAD_MODEL=PARSYNC
-test%-par: $(top_srcdir)/tests/test%.c force 
+test%-par: force 
 	@$(MAKE) `basename $@ -par` THREAD_MODEL=PAR
 
 tests-clean: 
 	@$(MAKE) -f $(top_builddir)/tests/Makefile clean
 
-run-tests:
-	@$(MAKE) -f $(top_builddir)/tests/Makefile run-tests \
+run-tests do-run-testexit:
+	@$(MAKE) -f $(top_builddir)/tests/Makefile $@ \
 	  CONDUIT_NAME=$(CONDUIT_NAME) \
-	  CONDUIT_RUNCMD="$(CONDUIT_RUNCMD)"
+	  CONDUIT_RUNCMD="$(CONDUIT_RUNCMD)" \
+	  CONDUIT_TESTS="$(CONDUIT_TESTS)"
 
 run-tests-seq: tests-clean tests-seq run-tests
 run-tests-par: tests-clean tests-par run-tests
 run-tests-parsync: tests-clean tests-parsync run-tests
 
-force:
+.PRECIOUS: run-testexit
+run-testexit: force
+	@if test ! -x testexit ; then \
+	  $(MAKE) testexit-par ; \
+	fi
+	@$(MAKE) do-run-testexit	
 
-do-all: $(libraries) $(makefile_fragments)
+force:
 
 do-clean-local: tests-clean
 	@echo rm -f $(makefile_fragments) $(libgasnet_objects) $(libraries) *.o core
 	@rm -f $(makefile_fragments) $(libgasnet_objects) $(libraries) *.o core
+	@rm -Rf .SEQ .PAR .PARSYNC
 
 
 do-install-data-local: force $(headers) $(makefile_fragments)
@@ -169,6 +206,11 @@ do-error:
 	@echo "       try re-running configure with --enable-$(CONDUIT_NAME)"
 	@exit 1
 
+do-pthreads-error: 
+	@echo "ERROR: pthreads support was not detected at configure time"
+	@echo "       try re-running configure with --enable-pthreads"
+	@exit 1
+
 $(top_builddir)/other/Makefile-conduit.mak: $(top_srcdir)/other/Makefile-conduit.mak.in
 	$(MAKE) -C $(top_builddir)/other Makefile-conduit.mak
 
@@ -188,9 +230,11 @@ $(CONDUIT_NAME)-seq.mak: conduit.mak $(top_builddir)/other/fragment-head.mak $(t
 	$(MAKE) do-make-fragment thread_model=seq THREAD_MODEL=SEQ
 
 $(CONDUIT_NAME)-par.mak: conduit.mak $(top_builddir)/other/fragment-head.mak $(top_builddir)/other/fragment-body.mak 
+	@@HAVE_PTHREAD_FALSE@$(MAKE) do-pthreads-error
 	$(MAKE) do-make-fragment thread_model=par THREAD_MODEL=PAR
 
 $(CONDUIT_NAME)-parsync.mak: conduit.mak $(top_builddir)/other/fragment-head.mak $(top_builddir)/other/fragment-body.mak 
+	@@HAVE_PTHREAD_FALSE@$(MAKE) do-pthreads-error
 	$(MAKE) do-make-fragment thread_model=parsync THREAD_MODEL=PARSYNC
 
 do-make-fragment: force
