Add (run-)tests-installed-{seq,par,parsync} targets
These targets function similarly to (run-)tests-{seq,par,parsync}
targets, except they use the GASNet library and headers from the
install prefix (where they must have been installed by a previous
invocation).

This is a useful way to validate the correctness of an installation.

Also add top-level make aliases tests-installed and test_install
to invoke these across all conduits.

diff --git a/other/Makefile-conduit.mak.in b/other/Makefile-conduit.mak.in
--- a/other/Makefile-conduit.mak.in
+++ b/other/Makefile-conduit.mak.in
@@ -85,6 +85,34 @@ tests-par: force libgasnet-$(CONDUIT_NAME)-par.a $(CONDUIT_NAME)-par.mak $(CONDU
 	  configfile="$(CONDUIT_NAME)-par.mak" \
 	  CONDUIT_TESTS="$(CONDUIT_TESTS)" $(CONDUIT_TEST_MAKEARGS)
 
+do-check-install: force
+	@if test -r $(DESTDIR)$(includedir)/$(CONDUIT_NAME)-conduit/$(CONDUIT_NAME)-seq.mak && \
+            test -r $(DESTDIR)$(libdir)/libgasnet-$(CONDUIT_NAME)-seq.a ; then :; else \
+            echo "ERROR: tests-installed-* targets require first running a top-level 'make install', but there does not appear to be a valid install for $(CONDUIT_NAME)-conduit in prefix=$(prefix)" ; \
+	    exit 1 ; \
+	 fi
+
+tests-installed-seq: do-check-install
+	@echo "*** Building all GASNet tests in SEQ/$(GASNET_SEGMENT_STR) mode against install in $(DESTDIR)$(libdir) ***"
+	$(MAKE) -f $(top_builddir)/tests/Makefile tests-seq \
+	  configfile="$(DESTDIR)$(includedir)/$(CONDUIT_NAME)-conduit/$(CONDUIT_NAME)-seq.mak" \
+	  tools_fragment="$(DESTDIR)$(includedir)/gasnet_tools-seq.mak" \
+	  CONDUIT_TESTS="$(CONDUIT_TESTS)" $(CONDUIT_TEST_MAKEARGS)
+
+tests-installed-par: do-check-install
+	@echo "*** Building all GASNet tests in PAR/$(GASNET_SEGMENT_STR) mode against install in $(DESTDIR)$(libdir) ***"
+	$(MAKE) -f $(top_builddir)/tests/Makefile tests-par \
+	  configfile="$(DESTDIR)$(includedir)/$(CONDUIT_NAME)-conduit/$(CONDUIT_NAME)-par.mak" \
+	  tools_fragment="$(DESTDIR)$(includedir)/gasnet_tools-par.mak" \
+	  CONDUIT_TESTS="$(CONDUIT_TESTS)" $(CONDUIT_TEST_MAKEARGS)
+
+tests-installed-parsync: do-check-install
+	@echo "*** Building all GASNet tests in parsync/$(GASNET_SEGMENT_STR) mode against install in $(DESTDIR)$(libdir) ***"
+	$(MAKE) -f $(top_builddir)/tests/Makefile tests-parsync \
+	  configfile="$(DESTDIR)$(includedir)/$(CONDUIT_NAME)-conduit/$(CONDUIT_NAME)-parsync.mak" \
+	  tools_fragment="$(DESTDIR)$(includedir)/gasnet_tools-parsync.mak" \
+	  CONDUIT_TESTS="$(CONDUIT_TESTS)" $(CONDUIT_TEST_MAKEARGS)
+
 tests-mpi: force 
 	@echo "*** Building all MPI tests ***"
 	@$(MAKE) -f $(top_builddir)/tests/Makefile tests-mpi \
