Merged from current GASNet Head, resolved conflicts and tested.
CVSMAIL: CC:

diff --git a/Bootstrap b/Bootstrap
--- a/Bootstrap
+++ b/Bootstrap
@@ -1,7 +1,7 @@
 #!/bin/sh
 #   $Source: /Users/kamil/work/gasnet-cvs2/gasnet/Bootstrap,v $
-#     $Date: 2006/10/03 19:15:52 $
-# $Revision: 1.16.2.3 $
+#     $Date: 2007/01/09 19:15:51 $
+# $Revision: 1.16.2.4 $
 # Description: GASNet developer Bootstrap script
 # Copyright 2004,  Dan Bonachea <bonachea@cs.berkeley.edu>
 # Terms of use are as specified in license.txt
@@ -83,7 +83,7 @@ fi
 if test "$NOTOOLCHECK" != "1" ; then
 missing=
 for autotool in autoconf autoheader automake aclocal m4 ; do
-  info=`( $autotool --version 2>/dev/null || echo 'Not found' ) | head -1`
+  info=`( $autotool --version 2>/dev/null < /dev/null || echo 'Not found' ) | head -1`
   if test "$info" != "Not found" ; then
     info="$info, in `which $autotool`"
   elif "$autotool" != "m4" ; then
@@ -153,8 +153,7 @@ set -x
     # back to $top_builddir w/o quoting it.
     # Add quotes around the offending command.
     mv configure .configure-orig
-    sed -e 's/^cache_file=\/dev\/null$/cache_file=.\/config.cache/' \
-        -e 's/cd $ac_popdir/cd "$ac_popdir"/' \
+    perl -pe 's@^cache_file=/dev/null$@cache_file=./config.cache@; s/cd \$ac_popdir/cd "\$ac_popdir"/;' \
         .configure-orig > configure
     chmod +x configure
     rm -f .configure-orig
