Update the SCI_DEV branch merge in all main branch changes up until today merge in the changes sent from UFL on 3/25/04

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -1,7 +1,7 @@
 ## Process this file with automake to produce Makefile.in	-*- makefile -*-
 #  $Archive:: /Ti/AMMPI/Makefile                                         $
-#     $Date: 2003/10/11 14:22:38 $
-# $Revision: 1.18.2.1 $
+#     $Date: 2004/03/29 17:46:16 $
+# $Revision: 1.18.2.2 $
 # Description: Makefile for GASNet 
 # Copyright 2002, Dan Bonachea <bonachea@cs.berkeley.edu>
 # Terms of use are as specified in license.txt
@@ -15,9 +15,10 @@ SUBDIRS =            \
         gm-conduit   \
         lapi-conduit \
 	mpi-conduit  \
+	sci-conduit  \
 	smp-conduit  \
-	vapi-conduit \
-	sci-conduit
+	udp-conduit  \
+	vapi-conduit
 
 configdir = $(includedir)
 config_DATA = $(CONFIG_HEADER)
@@ -28,7 +29,6 @@ headers =                  \
         gasnet_basic.h     \
         gasnet_handler.h   \
         gasnet_help.h      \
-        gasnet_internal.h  \
         gasnet_timer.h     \
 	gasnet_tools.h     \
 	gasnet_trace.h     
@@ -46,6 +46,7 @@ EXTRA_DIST =              \
         acconfig.h        \
         acinclude.m4      \
         $(headers)        \
+        gasnet_internal.h \
         gasnet_internal.c \
         gasnet_mmap.c 
 #       tests handled below
@@ -53,53 +54,63 @@ EXTRA_DIST =              \
 include_HEADERS = $(headers)
 
 force:
+
+# echo an arbitrary make/environment variable
+echovar: force
+	@echo $(VARNAME)=\"$($(VARNAME))\"
 	
-TEST_TYPE=tests-seq
+test: tests-seq
+tests: tests-seq
 
-tests: force
+other-tests:
 	@$(MAKE) -C $(top_builddir)/other all tests
-if USE_MPI_CONDUIT
-	@$(MAKE) -C $(top_builddir)/mpi-conduit all $(TEST_TYPE)
-endif
-if USE_GM_CONDUIT
-	@$(MAKE) -C $(top_builddir)/gm-conduit all $(TEST_TYPE)
-endif
-if USE_ELAN_CONDUIT
-	@$(MAKE) -C $(top_builddir)/elan-conduit all $(TEST_TYPE)
-endif
-if USE_LAPI_CONDUIT
-	@$(MAKE) -C $(top_builddir)/lapi-conduit all $(TEST_TYPE)
-endif
-if USE_SMP_CONDUIT
-	@$(MAKE) -C $(top_builddir)/smp-conduit all $(TEST_TYPE)
-endif
-if USE_VAPI_CONDUIT
-	@$(MAKE) -C $(top_builddir)/vapi-conduit all $(TEST_TYPE)
-endif
-if USE_SCI_CONDUIT
-	@$(MAKE) -C $(top_builddir)/sci-conduit all $(TEST_TYPE)
-endif
 
-test: tests
+other-run-tests:
+	@$(MAKE) -C $(top_builddir)/other run-tests
 
-tests-seq: 
-	$(MAKE) -C $(top_builddir) TEST_TYPE=tests-seq tests
+tests-seq: other-tests
+	@for conduit in $(CONDUITS) ; do                                      \
+	  $(MAKE) -C "$(top_builddir)/$$conduit-conduit" tests-seq || exit 1; \
+	done
 
-tests-par: 
-	$(MAKE) -C $(top_builddir) TEST_TYPE=tests-par tests
+tests-par: other-tests
+	@for conduit in $(CONDUITS) ; do                                      \
+	  $(MAKE) -C "$(top_builddir)/$$conduit-conduit" tests-par || exit 1; \
+	done
 
-tests-parsync: 
-	$(MAKE) -C $(top_builddir) TEST_TYPE=tests-parsync tests
+tests-parsync: other-tests
+	@for conduit in $(CONDUITS) ; do                                          \
+	  $(MAKE) -C "$(top_builddir)/$$conduit-conduit" tests-parsync || exit 1; \
+	done
 
-.PHONY: force clean tests test tests-seq tests-par tests-parsync
+run-tests: other-run-tests
+	@for conduit in $(CONDUITS) ; do                                      \
+	  $(MAKE) -C "$(top_builddir)/$$conduit-conduit" run-tests || exit 1; \
+	done
+
+run-tests-seq: tests-seq run-tests
+run-tests-par: tests-par run-tests
+run-tests-parsync: tests-parsync run-tests
+
+.PHONY: force clean tests test                                        \
+        other-tests other-run-tests tests-seq tests-par tests-parsync \
+        run-tests-seq run-tests-par run-tests-parsync
 
 dist-hook:
 	if test -f $(distdir)/docs/Makefile ; then \
           $(MAKE) -C $(distdir)/docs dist-hook ; \
         fi
+	mkdir -p $(distdir)/tests  # need this special hack to handle tests or distcheck will fail
+	fulldistdir=`cd $(distdir) ; pwd` export fulldistdir ; \
+        cd $(srcdir)/tests ; for file in `find . -print` ; do \
+ 	  if test -d $$file -a ! -d $$fulldistdir/tests/$$file ; then \
+	     mkdir -p $$fulldistdir/tests/$$file ; \
+          fi; \
+	  if test -f $$file -a ! -f $$fulldistdir/tests/$$file ; then \
+	     cp -p $$file $$fulldistdir/tests/$$file ; \
+          fi ; \
+        done
 	rm -Rf `find $(distdir) -name CVS -type d -print`
 	rm -f `find $(distdir) -name .#\* -print`
-	mkdir -p $(distdir)/tests  # need this special hack to handle tests or distcheck will fail
-	cp -Rp $(srcdir)/tests $(distdir)
 
 
diff --git a/tests/Makefile.in b/tests/Makefile.in
--- a/tests/Makefile.in
+++ b/tests/Makefile.in
@@ -1,35 +1,50 @@
-# $Header: /Users/kamil/work/gasnet-cvs2/gasnet/tests/Makefile.in,v 1.10 2003/09/13 16:58:36 bonachea Exp $
+# $Header: /Users/kamil/work/gasnet-cvs2/gasnet/tests/Makefile.in,v 1.10.2.1 2004/03/29 17:46:42 bonachea Exp $
 # Description: Makefile for GASNet tests
 # Copyright 2002, Dan Bonachea <bonachea@cs.berkeley.edu>
 # Terms of use are as specified in license.txt
 
-all:
+all: 
 	@echo This Makefile is not intended to be called directly
 	@echo do a "make tests-seq" or "make tests-par" within the conduit directory
 
 # linker to be used for MPI programs
 GASNET_MPI_LD = @MPI_CC@
 
+srcdir="@TOP_SRCDIR@/tests"
+
 configfile=/dev/null # must be overridden by caller
 include $(configfile)
 
+Makefile: @TOP_SRCDIR@/tests/Makefile.in
+	cd @TOP_BUILDDIR@ ; \
+	CONFIG_HEADERS= CONFIG_FILES=tests/Makefile ./config.status
+
 @USE_MPI_CONDUIT_TRUE@ MPI_TEST = testmpi
 
-testprograms_seq =  \
-	testam      \
-        testbarrier \
-	testcore1   \
-	testexit    \
-        testgasnet  \
-        testhsl     \
-        testlarge   \
-        testlogGP   \
-	testmisc    \
-        testsmall   \
-	testtools
+# tests that can be built in any mode
+# in order of most useful execution
+testprograms_seq =      \
+        testgasnet      \
+        testsmall       \
+        testlarge       \
+        testam          \
+        testcore1       \
+        testbarrier     \
+        testlogGP       \
+        testvis         \
+        testmisc        \
+        testalign       \
+        testrand        \
+        testexit        \
+        testhsl         \
+        testbarrierconf \
+        testbarrierlate \
+	testtools   
 
+# tests that should only be built in PARSYNC and PAR modes
 testprograms_parsync =  \
 
+# tests that should only be built in PAR mode
 testprograms_par =  \
 	testthreads \
 	$(MPI_TEST)
@@ -48,31 +63,116 @@ clean:
 distclean: 
 	rm -f Makefile
 
-# testtools is a special minimal case for an app that just uses GASNet tools
-testtools: force
-	@CC@ $(GASNET_INCLUDES) @GASNET_THREAD_DEFINES@ -DHAVE_PTHREAD_H -c -o $@.o $(srcdir)/$@.c
-	@CC@ -o $@ $@.o @GASNET_THREAD_LIBS@ @LIBS@ @LIBM@
+@GASNET_SEGMENT_FAST_TRUE@GASNET_SEGMENT_STR="FAST"
+@GASNET_SEGMENT_LARGE_TRUE@GASNET_SEGMENT_STR="LARGE"
+@GASNET_SEGMENT_EVERYTHING_TRUE@GASNET_SEGMENT_STR="EVERYTHING"
 
-# testlogGP needs an external file w/ the delay function.
-testlogGP: force delay.o
-	$(GASNET_CC) -I$(srcdir) $(GASNET_CPPFLAGS) $(GASNET_CFLAGS) -c -o $@.o $(srcdir)/$@.c
-	$(GASNET_LD) $(GASNET_LDFLAGS) -o $@ $@.o delay.o $(GASNET_LIBS)
-delay.o: $(srcdir)/delay.c
-	$(GASNET_CC) -O0 -c -o $@ $(srcdir)/$*.c
+# default node count
+TEST_NODES=2
+# provide args and node counts for specific tests, user overrides from EXTRA_PARAMS
+TEST_PARAMS=                    \
+   testcore1_args="1000";       \
+   testrand_args="1024";        \
+   testlogGP_args="1000 65536"; \
+   testthreads_args="-a 2";	\
+   testmisc_nodes="1";		\
+   $(EXTRA_PARAMS)
+
+# omit tests that are supposed to fail or known to cause failures
+testprograms_err =      \
+        testexit        \
+        testhsl         \
+	$(MPI_TEST)
+
+# tests that do not link libgasnet and should execute directly on the frontend with no spawner
+testprograms_nongasnet = \
+	testtools
+
+CONDUIT_NAME_UC=`echo $(CONDUIT_NAME) | @AWK@  '{print toupper($$0)}'`
+run-tests: force
+	@$(TEST_PARAMS)                                                                 \
+	export `echo "$(TEST_PARAMS)" | @AWK@ 'BEGIN {FS="=";RS=";"}{ print $$1 }'` ;   \
+	line='+++++++++++++++++++++++++++++++++++++++' ; line="$$line$$line" ;          \
+	tests_to_run="" export tests_to_run ;                                           \
+	tests_to_ignore="" export tests_to_ignore ;                                     \
+	for file in $(testprograms) ; do if test -x "$$file" ; then                     \
+	  if test "`echo \"$(testprograms_err)\"| grep $$file ; exit 0`"; then          \
+	    tests_to_ignore="$$tests_to_ignore $$file" ;                                \
+	  else                                                                          \
+	    tests_to_run="$$tests_to_run $$file" ;                                      \
+	  fi ;                                                                          \
+	fi ; done ;                                                                     \
+	echo $$line ;                                                                   \
+	echo " Running $(CONDUIT_NAME)-conduit tests:" ;                                \
+	for file in $$tests_to_run ; do echo "   $$file" ; done ;                       \
+	if test "$$tests_to_ignore" ; then                                              \
+	  echo " Ignoring tests: $$tests_to_ignore" ;                                   \
+	fi ;                                                                            \
+	echo " If this fails to spawn a job,"                                           \
+	     "you may need to re-run with a command like:" ;                            \
+	echo "  gmake run-tests $(CONDUIT_NAME_UC)_RUNCMD=\"$(CONDUIT_RUNCMD)\"" ;      \
+	echo $$line ;                                                                   \
+	TEST_RUNCMD="$$$(CONDUIT_NAME_UC)_RUNCMD" export TEST_RUNCMD ;                  \
+	TEST_RUNCMD="`eval echo $$TEST_RUNCMD`" ;                                       \
+	if test -z "$$TEST_RUNCMD" ; then                                               \
+	  TEST_RUNCMD="$(CONDUIT_RUNCMD)" ;                                             \
+	fi ;                                                                            \
+	for file in $$tests_to_run ; do                                                 \
+	    args="$$""$${file}_args" ;                                                  \
+	    args="`eval echo $$args`" ;                                                 \
+	    nodes="$$\{""$${file}_nodes-$(TEST_NODES)\}" ;                              \
+	    nodes="`eval eval echo $$nodes`" ;                                          \
+	    if test "`echo \"$(testprograms_nongasnet)\"| grep $$file ; exit 0`"; then  \
+	      echo "*** Running $(CONDUIT_NAME)-conduit $$file ***" ;                   \
+	      cmd="./$$file $$args" ;                                                   \
+	    else                                                                        \
+	      awk_threadscan='BEGIN {FS=" ";RS="$$"}                                    \
+		/GASNetThreadModel: [^ ]* / { split($$2,A,/_/); print A[2] ; exit}' ;   \
+	      threadmode=`cat -v $$file@EXESUFFIX@ 2> /dev/null |                       \
+                          eval @AWK@ \'$$awk_threadscan\'` ;                            \
+	      echo "*** Running $(CONDUIT_NAME)-conduit $$file"                         \
+		   "in $$threadmode/$(GASNET_SEGMENT_STR) mode ***" ;                   \
+	      awk_cmdbuild='{ gsub("%P","./'$$file'");                                  \
+			      gsub("%N","'$$nodes'");                                   \
+			      gsub("%A","'"$$args"'"); print $0 }' ;                    \
+	      cmd="`echo \"$$TEST_RUNCMD\" | eval @AWK@ \'$$awk_cmdbuild\'`" ;          \
+	    fi;                                                                         \
+	    echo "$$cmd" ;                                                              \
+	    /usr/bin/time $$cmd || echo "ERROR: Test exited with failure code=$$?" ;    \
+	    echo $$line ;                                                               \
+	done ;                                                                          \
+	echo "TESTS COMPLETE"
+
+# testtools is a special minimal case for an app that just uses GASNet tools
+# specifically, we carefully omit BUILDCONFIG_DEFINES
+testtools: force
+	@CC@ @CFLAGS@ @MISC_CFLAGS@ @MISC_CPPFLAGS@ $(GASNET_INCLUDES) @GASNET_THREAD_DEFINES@ -DHAVE_PTHREAD_H -c -o $@.o $(srcdir)/$@.c
+	@CC@ @CFLAGS@ @MISC_CFLAGS@ -o $@ $@.o @GASNET_THREAD_LIBS@ @LIBS@ @LIBM@
+	rm -f $@.o
+
+# some tests need delay.o
+testlogGP: delay.o
+testlogGP_extraobjs = delay.o
+testbarrierlate: delay.o
+testbarrierlate_extraobjs = delay.o
+
+# delay function, used by multiple tests
+delay.o: force
+	$(GASNET_CC) $(GASNET_INCLUDES) -c -o $@ $(srcdir)/$*.c
 
 # testmpi must be compiled like an MPI program with GASNet support
 testmpi: force
 	@MPI_CC@ -I$(srcdir) $(GASNET_CPPFLAGS) $(GASNET_CFLAGS) @MPI_CFLAGS@ -c -o $@.o $(srcdir)/$@.c
 	$(GASNET_MPI_LD) $(GASNET_LDFLAGS) @MPI_CFLAGS@ -o $@ $@.o @MPI_LIBS@ $(GASNET_LIBS)
-	
+	rm -f $@.o	
 
 # This is a model for how GASNet clients should be built:
 test% : force
 	$(GASNET_CC) -I$(srcdir) $(GASNET_CPPFLAGS) $(GASNET_CFLAGS) -c -o $@.o $(srcdir)/$@.c
-	$(GASNET_LD) $(GASNET_LDFLAGS) -o $@ $@.o $(GASNET_LIBS)
+	$(GASNET_LD) $(GASNET_LDFLAGS) -o $@ $@.o $($@_extraobjs) $(GASNET_LIBS)
+	rm -f $@.o
 
 force:
 	
 
 .PHONY: force all
-
