Bring portals-branch up to date with main gasnet branch before beginning development work on portals-conduit
CVSMAIL: CC:

diff --git a/tests/Makefile.in b/tests/Makefile.in
--- a/tests/Makefile.in
+++ b/tests/Makefile.in
@@ -1,6 +1,6 @@
 #   $Source: /Users/kamil/work/gasnet-cvs2/gasnet/tests/Makefile.in,v $
-#     $Date: 2005/11/11 06:48:40 $
-# $Revision: 1.72 $
+#     $Date: 2006/06/06 22:35:48 $
+# $Revision: 1.72.2.1 $
 # Description: Makefile for GASNet tests
 # @configure_input@
 # Copyright 2002, Dan Bonachea <bonachea@cs.berkeley.edu>
@@ -51,22 +51,23 @@ MPI2_TESTS = 			\
 #   please also add it to upcr/upc-tests/gasnet-tests/harness.conf
 testprograms_seq =      \
         testgasnet      \
+        testtools       \
+        testinternal    \
         testenv         \
+        testhsl         \
         testsmall       \
         testlarge       \
         testam          \
+        testmisc        \
         testcore1       \
         testbarrier     \
+        testbarrierconf \
+        testbarrierlate \
         testlogGP       \
-        testvis         \
-        testmisc        \
         testalign       \
         testrand        \
         testexit        \
-        testhsl         \
-        testbarrierconf \
-        testbarrierlate \
-        testtools       \
+        testvis         \
         testcoll        \
         testnbr    	\
 	testqueue	\
@@ -118,8 +119,9 @@ TEST_NODES=2
 # provide args and node counts for specific tests, user can override with MANUAL_TESTPARAMS
 TEST_PARAMS=                    					\
    testcore1_args="1000";       					\
+   testhsl_args="0";        						\
    testrand_args="1024";        					\
-   testlogGP_args="1000 8 65536";					\
+   testlogGP_args="1000 0 8 65536";					\
    testthreads_args="2";						\
    testmisc_nodes="1";							\
    testbarrierconf_nodes="3";						\
@@ -133,7 +135,6 @@ TEST_PARAMS=                    					\
 # omit tests that are supposed to fail or known to cause failures
 testprograms_err =      \
         testexit        \
-        testhsl         \
 	$(MPI_TESTS_SEQ) \
 	$(MPI_TESTS_PAR)
 
@@ -224,7 +225,7 @@ run-tests: force
 	    ( eval env GASNET_DUMMY=\"GASNet dummy value\" $(TEST_ENV)                  \
 	    $$TIMECMD $$cmd || echo "ERROR: Test exited with failure code=$$?" )        \
                              2>&1 | tee .test-output ;                                  \
-            failure=`grep -e ERROR -e 'fatal signal' .test-output |                     \
+            failure=`@PERL@ -ne 'print if (/ERROR/ || /fatal signal/);' .test-output |  \
                      grep -v 'Retrying allocation'` ;                                   \
             if test "$$failure" != "" ; then                                            \
                echo " " >> $(TESTLOG) ;                                                 \
@@ -258,48 +259,67 @@ do-run-testexit: force
 	@echo '  RUNCMD="$$INTERACTIVE_RUNCMD"'                   >> $(TESTEXIT_SCRIPT)
 	@echo "fi"                                                >> $(TESTEXIT_SCRIPT)
 	@echo "MALLOC_CHECK_=2; export MALLOC_CHECK_"             >> $(TESTEXIT_SCRIPT)
+	@if test "`echo ' mpi udp ' | grep ' $(CONDUIT_NAME) '`" != "" ; then \
+	   echo "have_interrupt=0"                                >> $(TESTEXIT_SCRIPT) ; \
+	 else                                                                             \
+	   echo "have_interrupt=1"                                >> $(TESTEXIT_SCRIPT) ; \
+	 fi
 	@echo 'echo "Starting run-testexit at: `date`"'           >> $(TESTEXIT_SCRIPT)
 	@echo 'ID="`hostname`-$$MP_CHILD$$PBS_NODENUM"'           >> $(TESTEXIT_SCRIPT)
+	@echo 'line="----------------------------------"'         >> $(TESTEXIT_SCRIPT)
+	@echo 'line="$$line$$line"'                               >> $(TESTEXIT_SCRIPT)
 	@i=0; \
-	 while test "$$i" != "$(TESTEXIT_SEQMAX)" ; do                       \
-           i=`expr $$i + 1`;                                                 \
-	   echo ""                                   >> $(TESTEXIT_SCRIPT) ; \
-	   echo 'echo "$$ID: testexit '$$i'"'        >> $(TESTEXIT_SCRIPT) ; \
-	   echo '$$RUNCMD'" $$i"                     >> $(TESTEXIT_SCRIPT) ; \
-	   echo 'echo "$$ID: result=$$?"'            >> $(TESTEXIT_SCRIPT) ; \
-	   echo "sleep 2"                            >> $(TESTEXIT_SCRIPT) ; \
-	 done ; \
-	 echo 'threadmode=`@PERL@ -n -e '"'"'$(perl_threadscan)'"'"' ' \
-              'testexit@EXESUFFIX@ 2> /dev/null`'      >> $(TESTEXIT_SCRIPT) ; \
-	 echo 'if test "$$threadmode" = "SEQ" -o ' \
-                   '"$$threadmode" = "PARSYNC" ; then' >> $(TESTEXIT_SCRIPT) ; \
-	 echo '  echo "WARNING: testexit was compiled' \
-              'in GASNET_$$threadmode mode"'           >> $(TESTEXIT_SCRIPT) ; \
-	 echo '  echo "WARNING: be sure to recompile the test in' \
-              'GASNET_PAR mode for full results"'      >> $(TESTEXIT_SCRIPT) ; \
-	 echo 'else' >> $(TESTEXIT_SCRIPT) ; \
+	 needinterrupt="5 9 16" ; export needinterrupt ;                        \
 	 while test "$$i" != "$(TESTEXIT_PARMAX)" ; do                       \
            i=`expr $$i + 1`;                                                 \
 	   echo ""                                   >> $(TESTEXIT_SCRIPT) ; \
+	   if test "`echo ' '$$needinterrupt' ' | grep ' '$$i' '`" != "" ; then  \
+	     echo 'if test "$$have_interrupt" = "1" ; then' >> $(TESTEXIT_SCRIPT) ; \
+	   fi ;                                                              \
+	   echo 'echo "$$line"'                      >> $(TESTEXIT_SCRIPT) ; \
 	   echo 'echo "$$ID: testexit '$$i'"'        >> $(TESTEXIT_SCRIPT) ; \
+	   echo 'echo "$$RUNCMD"'" $$i"              >> $(TESTEXIT_SCRIPT) ; \
 	   echo '$$RUNCMD'" $$i"                     >> $(TESTEXIT_SCRIPT) ; \
 	   echo 'echo "$$ID: result=$$?"'            >> $(TESTEXIT_SCRIPT) ; \
-	   echo "sleep 2"                            >> $(TESTEXIT_SCRIPT) ; \
+	   echo "sleep 1"                            >> $(TESTEXIT_SCRIPT) ; \
+	   if test "`echo ' '$$needinterrupt' ' | grep ' '$$i' '`" != "" ; then  \
+	     echo 'else'                             >> $(TESTEXIT_SCRIPT) ; \
+	     echo "echo 'Test $$i SKIPPED - conduit lacks interrupts'" >> $(TESTEXIT_SCRIPT) ; \
+	     echo 'fi'                               >> $(TESTEXIT_SCRIPT) ; \
+	   fi ;                                                              \
+	   if test "$$i" = "$(TESTEXIT_SEQMAX)" ; then                       \
+	     echo 'threadmode=`@PERL@ -n -e '"'"'$(perl_threadscan)'"'"' ' \
+                  'testexit@EXESUFFIX@ 2> /dev/null`'      >> $(TESTEXIT_SCRIPT) ; \
+	     echo 'if test "$$threadmode" = "SEQ" -o ' \
+                       '"$$threadmode" = "PARSYNC" ; then' >> $(TESTEXIT_SCRIPT) ; \
+	     echo '  echo "WARNING: testexit was compiled' \
+                  'in GASNET_$$threadmode mode"'           >> $(TESTEXIT_SCRIPT) ; \
+	     echo '  echo "WARNING: be sure to recompile the test in' \
+                  'GASNET_PAR mode for full results"'      >> $(TESTEXIT_SCRIPT) ; \
+	     echo 'else' >> $(TESTEXIT_SCRIPT) ; \
+	   fi ; \
 	 done ; \
 	 echo 'fi' >> $(TESTEXIT_SCRIPT) 
-	@echo 'echo "`hostname`: done."'  >> $(TESTEXIT_SCRIPT)
+	@echo 'echo "$$ID: done."'  >> $(TESTEXIT_SCRIPT)
 	@chmod +x $(TESTEXIT_SCRIPT)
 	@echo "Complete. Starting execution..."
 	@./$(TESTEXIT_SCRIPT)
 
+KEEPTMP_CFLAGS = $(patsubst %,@KEEPTMP_CFLAGS@,$(KEEPTMPS))
 
 # testtools is a special minimal case for an app that just uses GASNet tools
-# specifically, we carefully omit BUILDCONFIG_DEFINES
-@BUILDCONFIG_DEBUG_FALSE@ TOOLS_CPPFLAGS = -DNDEBUG
+@BUILDCONFIG_DEBUG_FALSE@ TESTTOOLS_DEBUGFLAGS = -DNDEBUG
+@HAVE_PTHREAD_TRUE@       TESTTOOLS_THREADFLAGS = -DGASNETT_THREAD_SAFE @GASNET_THREAD_DEFINES@
+@HAVE_PTHREAD_TRUE@       TESTTOOLS_TOOLLIB_NAME = gasnet_tools-par
+@HAVE_PTHREAD_TRUE@       TESTTOOLS_TOOLLIB = -L@TOP_BUILDDIR@ -l$(TESTTOOLS_TOOLLIB_NAME) @GASNET_THREAD_LIBS@
+@HAVE_PTHREAD_FALSE@      TESTTOOLS_TOOLLIB_NAME = gasnet_tools-seq
+@HAVE_PTHREAD_FALSE@      TESTTOOLS_TOOLLIB = -L@TOP_BUILDDIR@ -l$(TESTTOOLS_TOOLLIB_NAME)
+TOOLS_CPPFLAGS = $(TESTTOOLS_DEBUGFLAGS) $(TESTTOOLS_THREADFLAGS)
 testtools: force
-	@CC@ @CFLAGS@ @MISC_CFLAGS@ @MISC_CPPFLAGS@ $(GASNET_INCLUDES) @GASNET_THREAD_DEFINES@ $(TOOLS_CPPFLAGS) $(MANUAL_CFLAGS) -c -o $@.o $(srcdir)/$@.c
-	@CC@ @CFLAGS@ @MISC_CFLAGS@ -o $@ $@.o @GASNET_THREAD_LIBS@ @LIBS@ @LIBM@
-	rm -f $@.o
+	@cd .. && $(MAKE) lib$(TESTTOOLS_TOOLLIB_NAME).a
+	@CC@ @CFLAGS@ @MISC_CFLAGS@ @MISC_CPPFLAGS@ $(GASNET_INCLUDES) $(TOOLS_CPPFLAGS) $(KEEPTMP_CFLAGS) $(MANUAL_CFLAGS) -c -o $@.o $(srcdir)/$@.c
+	@CC@ @CFLAGS@ @MISC_CFLAGS@ @LDFLAGS@ $(MANUAL_LDFLAGS) -o $@ $@.o $(TESTTOOLS_TOOLLIB) @LIBS@ @LIBM@ $(MANUAL_LIBS)
+	@test -n '$(KEEPTMPS)' || ( cmd="rm -f $@.o"; echo "$$cmd"; eval "$$cmd" )
 
 # some tests need delay.o
 testlogGP: delay.o
@@ -311,33 +331,37 @@ testbarrierlate_extraobjs = delay.o
 # need to deliberately exclude optimization for this object file to prevent breaking delay
 # some compilers implicitly enable optimization, so don't complain about that
 delay.o: force
-	$(GASNET_CC) $(GASNET_CPPFLAGS) $(GASNET_MISC_CFLAGS) $(MANUAL_CFLAGS) -DGASNET_ALLOW_OPTIMIZED_DEBUG -c -o $@ $(srcdir)/$*.c
+	$(GASNET_CC) $(GASNET_CPPFLAGS) $(GASNET_MISC_CFLAGS) $(KEEPTMP_CFLAGS) $(MANUAL_CFLAGS) -DGASNET_ALLOW_OPTIMIZED_DEBUG -c -o $@ $(srcdir)/$*.c
 
 # testmpi must be compiled like an MPI program with GASNet support
 testmpi: force
-	@MPI_CC@ -I$(srcdir) $(GASNET_CPPFLAGS) @MPI_CFLAGS@ $(MANUAL_CFLAGS) -c -o $@.o $(srcdir)/$@.c
+	@MPI_CC@ -I$(srcdir) $(GASNET_CPPFLAGS) @MPI_CFLAGS@ $(KEEPTMP_CFLAGS) $(MANUAL_CFLAGS) -c -o $@.o $(srcdir)/$@.c
 	$(GASNET_MPI_LD) $(GASNET_LDFLAGS) @MPI_CFLAGS@ -o $@ $@.o @MPI_LIBS@ $(GASNET_LIBS)
-	rm -f $@.o	
+	@test -n '$(KEEPTMPS)' || ( cmd="rm -f $@.o"; echo "$$cmd"; eval "$$cmd" )
 
 # the following are just plain MPI programs
 # testmpinbr requires libm
 $(MPI_TESTS): force
-	@MPI_CC@ -I$(srcdir)/mpi -I@TOP_SRCDIR@/other @MPI_CFLAGS@ $(MANUAL_CFLAGS) -c -o $@.o $(srcdir)/mpi/$@.c
-	$(GASNET_MPI_LD) $(GASNET_LDFLAGS) @MPI_CFLAGS@ -o $@ $@.o @MPI_LIBS@ @LIBM@
-	rm -f $@.o	
+	@MPI_CC@ -I$(srcdir)/mpi -I@TOP_SRCDIR@/other @MPI_CFLAGS@ $(KEEPTMP_CFLAGS) $(MANUAL_CFLAGS) -c -o $@.o $(srcdir)/mpi/$@.c
+	$(GASNET_MPI_LD) $(GASNET_LDFLAGS) @MPI_CFLAGS@ -o $@ $@.o @MPI_LIBS@ @LIBM@ $(MANUAL_LIBS)
+	@test -n '$(KEEPTMPS)' || ( cmd="rm -f $@.o"; echo "$$cmd"; eval "$$cmd" )
 
 # testcxx tests support for compiling a C++-based GASNet client 
 # this is unlikely to work on conduits requiring a special linker (eg mpi-conduit)
 testcxx: force
-	@CXX@ @CXXFLAGS@ @MISC_CXXFLAGS@ -I$(srcdir) $(GASNET_CPPFLAGS) $(MANUAL_CFLAGS) -c -o $@.o $(srcdir)/$@.cc
+	@if test -z "@CXX@"; then \
+		echo "ERROR: testcxx target requested, but no c++ compiler is configured"; \
+		exit 1; \
+	 fi
+	@CXX@ @CXXFLAGS@ @MISC_CXXFLAGS@ -I$(srcdir) $(GASNET_DEFINES) $(GASNET_INCLUDES) $(KEEPTMP_CFLAGS) $(MANUAL_CXXFLAGS) -c -o $@.o $(srcdir)/$@.cc
 	@CXX@ @CXXFLAGS@ $(GASNET_LDFLAGS) -o $@ $@.o $($@_extraobjs) $(GASNET_LIBS)
-	rm -f $@.o
+	@test -n '$(KEEPTMPS)' || ( cmd="rm -f $@.o"; echo "$$cmd"; eval "$$cmd" )
 
 # This is a model for how GASNet clients should be built:
 test% : force
-	$(GASNET_CC) -I$(srcdir) $(GASNET_CPPFLAGS) $(GASNET_CFLAGS) -c -o $@.o $(srcdir)/$@.c
+	$(GASNET_CC) -I$(srcdir) $(GASNET_CPPFLAGS) $(KEEPTMP_CFLAGS) $(GASNET_CFLAGS) -c -o $@.o $(srcdir)/$@.c
 	$(GASNET_LD) $(GASNET_LDFLAGS) -o $@ $@.o $($@_extraobjs) $(GASNET_LIBS)
-	rm -f $@.o
+	@test -n '$(KEEPTMPS)' || ( cmd="rm -f $@.o"; echo "$$cmd"; eval "$$cmd" )
 
 force:
 	
