* Merged with current GASNet HEAD branch. * Added weakatomic gasnete_putget_poll_cnt as a counter on the number of Put/Get   operations that have been initiated since the last polling operation.   This value is cleared by the Portals progress function.   It is incremented on each Put/Get.   If the value exceeds gasnete_max_poll_events the Put/Get will call the Portals   progress function.  This is to insure we do not build up too many Portals events   during periods of active non-blocking puts and gets.  The limit is settable   through an environment variable.
CVSMAIL: CC:

diff --git a/tests/Makefile.in b/tests/Makefile.in
--- a/tests/Makefile.in
+++ b/tests/Makefile.in
@@ -1,6 +1,6 @@
 #   $Source: /Users/kamil/work/gasnet-cvs2/gasnet/tests/Makefile.in,v $
-#     $Date: 2006/07/10 23:57:01 $
-# $Revision: 1.72.2.2 $
+#     $Date: 2006/08/08 16:36:49 $
+# $Revision: 1.72.2.3 $
 # Description: Makefile for GASNet tests
 # @configure_input@
 # Copyright 2002, Dan Bonachea <bonachea@cs.berkeley.edu>
@@ -26,6 +26,9 @@ Makefile: @TOP_SRCDIR@/tests/Makefile.in
 # GASNet-related MPI tests
 @USE_MPI_COMPAT_TRUE@ MPI_TESTS_SEQ = 
 @USE_MPI_COMPAT_TRUE@ MPI_TESTS_PAR = testmpi
+
+# C++ tests
+CXX_TESTS = testcxx testtoolscxx
 
 # non-GASNet plain MPI tests
 MPI1_TESTS = 			\
@@ -86,7 +89,7 @@ testprograms_par =  \
 	testcontend \
 	$(MPI_TESTS_PAR)
 
-testprograms = $(testprograms_seq) $(testprograms_parsync) $(testprograms_par) $(MPI_TESTS)
+testprograms = $(testprograms_seq) $(testprograms_parsync) $(testprograms_par) $(MPI_TESTS) $(CXX_TESTS)
 
 tests-seq: clean $(testprograms_seq)
 	
@@ -144,7 +147,7 @@ testprograms_err =      \
 # tests that do not link libgasnet and should execute directly on the frontend with no spawner
 # (except in the case of cross-compilation, where we run them on the compute node using MPIRUN_CMD)
 testprograms_nongasnet = \
-	testtools
+	testtools testtoolscxx
 
 CONDUIT_NAME_UC=`echo $(CONDUIT_NAME) | @AWK@  '{print toupper($$0)}'`
 awk_cmdbuild={  qargs="'"'"$$args"'"'"; gsub("'"'"\x22"'"'","'"'"\x5C\x22"'"'",qargs); \
@@ -322,6 +325,17 @@ testtools: force
 	@cd .. && $(MAKE) lib$(TESTTOOLS_TOOLLIB_NAME).a
 	@CC@ @CFLAGS@ @MISC_CFLAGS@ @MISC_CPPFLAGS@ $(GASNET_INCLUDES) $(TOOLS_CPPFLAGS) $(KEEPTMP_CFLAGS) $(MANUAL_CFLAGS) -c -o $@.o $(srcdir)/$@.c
 	@CC@ @CFLAGS@ @MISC_CFLAGS@ @LDFLAGS@ $(MANUAL_LDFLAGS) -o $@ $@.o $(TESTTOOLS_TOOLLIB) @LIBS@ @LIBM@ $(MANUAL_LIBS)
+	@test -n '$(KEEPTMPS)' || ( cmd="rm -f $@.o"; echo "$$cmd"; eval "$$cmd" )
+
+# As above w/ a c++ tools client
+testtoolscxx: force
+	@if test -z "@CXX@"; then \
+		echo "ERROR: testtoolscxx target requested, but no c++ compiler is configured"; \
+		exit 1; \
+	 fi
+	@cd .. && $(MAKE) lib$(TESTTOOLS_TOOLLIB_NAME).a
+	@CXX@ @CXXFLAGS@ @MISC_CXXFLAGS@ @MISC_CPPFLAGS@ $(GASNET_INCLUDES) $(TOOLS_CPPFLAGS) $(KEEPTMP_CFLAGS) $(MANUAL_CXXFLAGS) -c -o $@.o $(srcdir)/$@.cc
+	@CXX@ @CXXFLAGS@ @MISC_CXXFLAGS@ @LDFLAGS@ $(MANUAL_LDFLAGS) -o $@ $@.o $(TESTTOOLS_TOOLLIB) @LIBS@ @LIBM@ $(MANUAL_LIBS)
 	@test -n '$(KEEPTMPS)' || ( cmd="rm -f $@.o"; echo "$$cmd"; eval "$$cmd" )
 
 # some tests need delay.o
