Merge head into SHMEM branch
This incorporates the latest changes to gasnet, and slurps
vapi-conduit, udp-conduit and amudp into the shmem branch.

diff --git a/elan-conduit/Makefile.am b/elan-conduit/Makefile.am
--- a/elan-conduit/Makefile.am
+++ b/elan-conduit/Makefile.am
@@ -1,5 +1,5 @@
 ## Process this file with automake to produce Makefile.in	-*- makefile -*-
-# $Header: /Users/kamil/work/gasnet-cvs2/gasnet/elan-conduit/Attic/Makefile.am,v 1.14 2003/10/29 00:46:36 phargrov Exp $
+# $Header: /Users/kamil/work/gasnet-cvs2/gasnet/elan-conduit/Attic/Makefile.am,v 1.14.4.1 2004/01/23 23:22:13 csbell Exp $
 # Description: Makefile for GASNet elan conduit
 # Copyright 2002, Dan Bonachea <bonachea@cs.berkeley.edu>
 # Terms of use are as specified in license.txt 
@@ -40,6 +40,7 @@ libgasnet_sources =                  \
 
 libgasnet_dependencies = $(filelist) $(libgasnet_sources) \
                          $(top_srcdir)/*.[ch]             \
+                         $(top_srcdir)/extended-ref/gasnet_extended_refbarrier.c \
                          $(top_srcdir)/extended-ref/*.h      
 			  
 libgasnet_objects =      \
@@ -113,14 +114,19 @@ install-data-local: $(headers)
 	@list='$(makefile_fragments)'; for p in $$list; do \
 	  if test -f $$p; then \
 	    filename=`basename $$p`; \
-	    echo " grep -v "###NOINSTALL###" $$p > $(DESTDIR)$(includedir)/elan-conduit/$$filename"; \
-	    grep -v "###NOINSTALL###" $$p > $(DESTDIR)$(includedir)/elan-conduit/$$filename; \
+	    echo "@GASNET_INSTALL_CMD@ < $$p > $(DESTDIR)$(includedir)/elan-conduit/$$filename"; \
+	    @GASNET_INSTALL_CMD@ < $$p > $(DESTDIR)$(includedir)/elan-conduit/$$filename; \
 	  else :; fi; \
 	done
 
 uninstall-local:
 	rm -f $(DESTDIR)$(includedir)/elan-conduit/*.h $(DESTDIR)$(includedir)/elan-conduit/*.mak
 
+else
+$(top_srcdir)/gasnet.h: force
+	@echo "ERROR: elan-conduit support was not detected at configure time"
+	@echo "       try re-running configure with --enable-elan"
+	@exit 1
 endif
 
 tests:
diff --git a/gm-conduit/Makefile.am b/gm-conduit/Makefile.am
--- a/gm-conduit/Makefile.am
+++ b/gm-conduit/Makefile.am
@@ -1,5 +1,5 @@
 ## Process this file with automake to produce Makefile.in	-*- makefile -*-
-# $Header: /Users/kamil/work/gasnet-cvs2/gasnet/gm-conduit/Attic/Makefile.am,v 1.29 2003/10/29 00:46:38 phargrov Exp $
+# $Header: /Users/kamil/work/gasnet-cvs2/gasnet/gm-conduit/Attic/Makefile.am,v 1.29.4.1 2004/01/23 23:22:16 csbell Exp $
 # Description: Makefile for GASNet gm conduit
 # Copyright 2002, Christian Bell <csbell@cs.berkeley.edu>
 # Copyright 2002, Dan Bonachea <bonachea@cs.berkeley.edu>
@@ -46,6 +46,8 @@ libgasnet_sources = $(srcdir)/gasnet_core.c $(srcdir)/gasnet_core_receive.c \
 		    $(srcdir)/gasnet_extended_firehose.c $(othersourcefiles)
 libgasnet_dependencies = $(filelist) $(libgasnet_sources) \
                          $(top_srcdir)/*.[ch] \
+                         $(top_srcdir)/extended-ref/gasnet_extended_refbarrier.c \
+                         $(top_srcdir)/extended-ref/*.h \
                          $(fh_srcdir)/firehose.h $(fh_srcdir)/firehose_internal.h
 libgasnet_objects = gasnet_core.o gasnet_internal.o gasnet_extended.o \
 		    gasnet_core_receive.o gasnet_core_conf.o gasnet_extended_op.o \
@@ -116,14 +118,19 @@ install-data-local: $(headers)
 	@list='$(makefile_fragments)'; for p in $$list; do \
 	  if test -f $$p; then \
 	    filename=`basename $$p`; \
-	    echo " grep -v "###NOINSTALL###" $$p > $(DESTDIR)$(includedir)/gm-conduit/$$filename"; \
-	    grep -v "###NOINSTALL###" $$p > $(DESTDIR)$(includedir)/gm-conduit/$$filename; \
+	    echo "@GASNET_INSTALL_CMD@ < $$p > $(DESTDIR)$(includedir)/gm-conduit/$$filename"; \
+	    @GASNET_INSTALL_CMD@ < $$p > $(DESTDIR)$(includedir)/gm-conduit/$$filename; \
 	  else :; fi; \
 	done
 
 uninstall-local:
 	rm -f $(includedir)/gm-conduit/*.h $(includedir)/gm-conduit/*.mak
 
+else
+$(top_srcdir)/gasnet.h: force
+	@echo "ERROR: gm-conduit support was not detected at configure time"
+	@echo "       try re-running configure with --enable-gm"
+	@exit 1
 endif
 
 tests:
diff --git a/lapi-conduit/Makefile.am b/lapi-conduit/Makefile.am
--- a/lapi-conduit/Makefile.am
+++ b/lapi-conduit/Makefile.am
@@ -1,5 +1,5 @@
 ## Process this file with automake to produce Makefile.in	-*- makefile -*-
-# $Header: /Users/kamil/work/gasnet-cvs2/gasnet/lapi-conduit/Attic/Makefile.am,v 1.16 2003/10/29 00:46:39 phargrov Exp $
+# $Header: /Users/kamil/work/gasnet-cvs2/gasnet/lapi-conduit/Attic/Makefile.am,v 1.16.4.1 2004/01/23 23:22:18 csbell Exp $
 # Description: Makefile for GASNet lapi conduit
 # Copyright 2002, Dan Bonachea <bonachea@cs.berkeley.edu>
 # Terms of use are as specified in license.txt
@@ -101,14 +101,19 @@ install-data-local: $(headers)
 	@list='$(makefile_fragments)'; for p in $$list; do \
 	  if test -f $$p; then \
 	    filename=`basename $$p`; \
-	    echo " grep -v "###NOINSTALL###" $$p > $(DESTDIR)$(includedir)/lapi-conduit/$$filename"; \
-	    grep -v "###NOINSTALL###" $$p > $(DESTDIR)$(includedir)/lapi-conduit/$$filename; \
+	    echo "@GASNET_INSTALL_CMD@ < $$p > $(DESTDIR)$(includedir)/lapi-conduit/$$filename"; \
+	    @GASNET_INSTALL_CMD@ < $$p > $(DESTDIR)$(includedir)/lapi-conduit/$$filename; \
 	  else :; fi; \
 	done
 
 uninstall-local:
 	rm -f $(DESTDIR)$(includedir)/lapi-conduit/*.h $(DESTDIR)$(includedir)/lapi-conduit/*.mak
 
+else
+$(top_srcdir)/gasnet.h: force
+	@echo "ERROR: lapi-conduit support was not detected at configure time"
+	@echo "       try re-running configure with --enable-lapi"
+	@exit 1
 endif
 
 tests:
diff --git a/mpi-conduit/Makefile.am b/mpi-conduit/Makefile.am
--- a/mpi-conduit/Makefile.am
+++ b/mpi-conduit/Makefile.am
@@ -1,5 +1,5 @@
 ## Process this file with automake to produce Makefile.in	-*- makefile -*-
-# $Header: /Users/kamil/work/gasnet-cvs2/gasnet/mpi-conduit/Makefile.am,v 1.15 2003/11/09 00:53:42 phargrov Exp $
+# $Header: /Users/kamil/work/gasnet-cvs2/gasnet/mpi-conduit/Makefile.am,v 1.15.4.1 2004/01/23 23:22:20 csbell Exp $
 # Description: Makefile for GASNet MPI conduit
 # Copyright 2002, Dan Bonachea <bonachea@cs.berkeley.edu>
 # Terms of use are as specified in license.txt
@@ -33,6 +33,7 @@ libgasnet_sources = $(srcdir)/gasnet_core.c     \
 
 libgasnet_dependencies = $(filelist) $(libgasnet_sources) \
                          $(top_srcdir)/*.[ch]             \
+                         $(top_srcdir)/extended-ref/gasnet_extended_refbarrier.c \
                          $(top_srcdir)/extended-ref/*.h   \
 			 $(top_srcdir)/other/ammpi/*.h
 
@@ -99,8 +100,8 @@ install-data-local: $(headers)
 	@list='$(makefile_fragments)'; for p in $$list; do \
 	  if test -f $$p; then \
 	    filename=`basename $$p`; \
-	    echo " grep -v "###NOINSTALL###" $$p > $(DESTDIR)$(includedir)/mpi-conduit/$$filename"; \
-	    grep -v "###NOINSTALL###" $$p > $(DESTDIR)$(includedir)/mpi-conduit/$$filename; \
+	    echo "@GASNET_INSTALL_CMD@ < $$p > $(DESTDIR)$(includedir)/mpi-conduit/$$filename"; \
+	    @GASNET_INSTALL_CMD@ < $$p > $(DESTDIR)$(includedir)/mpi-conduit/$$filename; \
 	  else :; fi; \
 	done
 
@@ -108,6 +109,11 @@ install-data-local: $(headers)
 uninstall-local:
 	rm -f $(DESTDIR)$(includedir)/mpi-conduit/*.h $(DESTDIR)$(includedir)/mpi-conduit/*.mak
 
+else
+$(top_srcdir)/gasnet.h: force
+	@echo "ERROR: mpi-conduit support was not detected at configure time"
+	@echo "       try re-running configure with --enable-mpi"
+	@exit 1
 endif
 
 tests:
diff --git a/template-conduit/Makefile.am b/template-conduit/Makefile.am
--- a/template-conduit/Makefile.am
+++ b/template-conduit/Makefile.am
@@ -1,5 +1,5 @@
 ## Process this file with automake to produce Makefile.in	-*- makefile -*-
-# $Header: /Users/kamil/work/gasnet-cvs2/gasnet/template-conduit/Makefile.am,v 1.15 2003/10/29 00:46:43 phargrov Exp $
+# $Header: /Users/kamil/work/gasnet-cvs2/gasnet/template-conduit/Makefile.am,v 1.15.4.1 2004/01/23 23:22:28 csbell Exp $
 # Description: Makefile for GASNet <conduitname> conduit
 # Copyright 2002, Dan Bonachea <bonachea@cs.berkeley.edu>
 # Terms of use are as specified in license.txt
@@ -31,6 +31,7 @@ EXTRA_DIST = $(filelist) \
 libgasnet_sources = $(srcdir)/gasnet_core.c $(othersourcefiles)
 libgasnet_dependencies = $(filelist) $(libgasnet_sources) \
                          $(top_srcdir)/*.[ch]             \
+                         $(top_srcdir)/extended-ref/gasnet_extended_refbarrier.c \
                          $(top_srcdir)/extended-ref/*.h       
 libgasnet_objects = gasnet_core.o gasnet_internal.o gasnet_extended.o
 
@@ -95,14 +96,19 @@ install-data-local: $(headers)
 	@list='$(makefile_fragments)'; for p in $$list; do \
 	  if test -f $$p; then \
 	    filename=`basename $$p`; \
-	    echo " grep -v "###NOINSTALL###" $$p > $(DESTDIR)$(includedir)/<conduitname>-conduit/$$filename"; \
-	    grep -v "###NOINSTALL###" $$p > $(DESTDIR)$(includedir)/<conduitname>-conduit/$$filename; \
+	    echo "@GASNET_INSTALL_CMD@ < $$p > $(DESTDIR)$(includedir)/template-conduit/$$filename"; \
+	    @GASNET_INSTALL_CMD@ < $$p > $(DESTDIR)$(includedir)/template-conduit/$$filename; \
 	  else :; fi; \
 	done
 
 uninstall-local:
 	rm -f $(DESTDIR)$(includedir)/<conduitname>-conduit/*.h $(DESTDIR)$(includedir)/<conduitname>-conduit/*.mak
 
+else
+$(top_srcdir)/gasnet.h: force
+	@echo "ERROR: <conduitname>-conduit support was not detected at configure time"
+	@echo "       try re-running configure with --enable-<conduitname>"
+	@exit 1
 endif
 
 tests:
diff --git a/vapi-conduit/Makefile.am b/vapi-conduit/Makefile.am
--- a/vapi-conduit/Makefile.am
+++ b/vapi-conduit/Makefile.am
@@ -1,5 +1,5 @@
 ## Process this file with automake to produce Makefile.in	-*- makefile -*-
-# $Header: /Users/kamil/work/gasnet-cvs2/gasnet/vapi-conduit/Attic/Makefile.am,v 1.7 2003/11/09 00:53:44 phargrov Exp $
+# $Header: /Users/kamil/work/gasnet-cvs2/gasnet/vapi-conduit/Attic/Makefile.am,v 1.7.4.1 2004/01/23 23:22:31 csbell Exp $
 # Description: Makefile for GASNet vapi conduit
 # Copyright 2002, Dan Bonachea <bonachea@cs.berkeley.edu>
 # Terms of use are as specified in license.txt
@@ -41,6 +41,7 @@ libgasnet_sources =                    \
       $(othersourcefiles)
 libgasnet_dependencies = $(filelist) $(libgasnet_sources) \
                          $(top_srcdir)/*.[ch]             \
+                         $(top_srcdir)/extended-ref/gasnet_extended_refbarrier.c \
                          $(top_srcdir)/extended-ref/*.h       
 libgasnet_objects = gasnet_core.o gasnet_core_sndrcv.o gasnet_bootstrap_mpi.o gasnet_internal.o gasnet_extended.o
 
@@ -105,14 +106,19 @@ install-data-local: $(headers)
 	@list='$(makefile_fragments)'; for p in $$list; do \
 	  if test -f $$p; then \
 	    filename=`basename $$p`; \
-	    echo " grep -v "###NOINSTALL###" $$p > $(DESTDIR)$(includedir)/vapi-conduit/$$filename"; \
-	    grep -v "###NOINSTALL###" $$p > $(DESTDIR)$(includedir)/vapi-conduit/$$filename; \
+	    echo "@GASNET_INSTALL_CMD@ < $$p > $(DESTDIR)$(includedir)/vapi-conduit/$$filename"; \
+	    @GASNET_INSTALL_CMD@ < $$p > $(DESTDIR)$(includedir)/vapi-conduit/$$filename; \
 	  else :; fi; \
 	done
 
 uninstall-local:
 	rm -f $(DESTDIR)$(includedir)/vapi-conduit/*.h $(DESTDIR)$(includedir)/vapi-conduit/*.mak
 
+else
+$(top_srcdir)/gasnet.h: force
+	@echo "ERROR: vapi-conduit support was not detected at configure time"
+	@echo "       try re-running configure with --enable-vapi"
+	@exit 1
 endif
 
 tests:
